scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'app'
    basic_auth:
      username: 'mon'
      password: 'monme'
    scrape_interval: 10s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['localhost:8080']
